window.FILMES_JSON = [
   {
    "tipo": "serie",
    "id": "6184",
    "title": "Caçador de Demônios - Episódio 1 - Pot O'Gold",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode1PotOGold.mp4",
    "duration": "34m",
    "release_year": "2025",
    "categories": "Séries, Dublagem, Acção",
    "cast": ["Kevin Bacon", "Jennifer Nettles", "Beth Grant"],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6185",
    "title": "Caçador de Demônios - Episódio 2 - Valacor",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode2Valacor.mp4",
    "duration": "27m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6186",
    "title": "Caçador de Demônios - Episódio 3 - Marphos",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode3Marphos.mp4",
    "duration": "31m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6187",
    "title": "Caçador de Demônios - Episódio 4 - Erdos",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode4Erdos.mp4",
    "duration": "28m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6188",
    "title": "Caçador de Demônios - Episódio 5 - Slypharis",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode5Slypharis.mp4",
    "duration": "29m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6189",
    "title": "Caçador de Demônios - Episódio 6 - Revelations",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode5Slypharis.mp4",
    "duration": "29m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6190",
    "title": "Caçador de Demônios - Episódio 7 - Pyralis",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode7Pyralis.mp4",
    "duration": "25m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6191",
    "title": "Caçador de Demônios - Episódio 8 - Lilith",
    "image": "",
    "description": "O caçador de recompensas Hub Halloran é ressuscitado pelo Diabo para capturar e enviar de volta os demônios que escaparam da prisão do Inferno. Nessa jornada, com a ajuda e os obstáculos criados por sua família distante, Hub descobre que foram seus próprios pecados que condenaram sua alma, o que o leva a buscar uma segunda chance na vida, no amor e na música country.",
    "video_url": "http://cinetop.co.mz:8330/film/CacadordeDemoniosEpisode8Lilith.mp4",
    "duration": "28m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "filme",
    "id": "3070",
    "title": "The Voyeurs",
    "image": "",
    "description": "Pippa e Thomas se mudam para o apartamento dos seus sonhos. Do outro lado da rua, um casal instável e atraente cativa os dois. Quando tentam interceder anonimamente em suas vidas, involuntariamente desencadeiam eventos que levarão ao desastre.",
    "video_url": "http://cinetop.co.mz:8330/film/TheVoyeurs.mp4",
    "duration": "116m",
    "release_year": "2021",
    "categories": "Drama, Novos Filmes, Mais de 18",
    "cast": ["Justice Smith", "Sydney Sweeney", "Ben Hardy"],
    "lang": "Português"
  },
  
  {
    "tipo": "serie",
    "id": "6344",
    "title": "Spartacus: House of Ashur - Episódio 1 - Episode 1",
    "image": "",
    "description": "E se Ashur tivesse sobrevivido e ganhado o ludus onde antes sangrou? Com Achillia, uma gladiadora, ele cria espetáculos que desafiam Roma e chocam a elite.",
    "video_url": "http://cinetop.co.mz:8330/film/SpartacusHouseofAshurEpisode1.mp4",
    "duration": "57m",
    "release_year": "2026",
    "categories": "Séries, Novos Filmes, Dublagem, Aventura",
    "cast": [
      "Nick E. Tarabay",
      "Graham McTavish",
      "Tenika Davis"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6345",
    "title": "Spartacus: House of Ashur - Episódio 2 - Episode 2",
    "image": "",
    "description": "E se Ashur tivesse sobrevivido e ganhado o ludus onde antes sangrou? Com Achillia, uma gladiadora, ele cria espetáculos que desafiam Roma e chocam a elite.",
    "video_url": "http://cinetop.co.mz:8330/film/SpartacusHouseofAshurEpisode2.mp4",
    "duration": "57m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6346",
    "title": "Spartacus: House of Ashur - Episódio 3 - Episode 3",
    "image": "",
    "description": "E se Ashur tivesse sobrevivido e ganhado o ludus onde antes sangrou? Com Achillia, uma gladiadora, ele cria espetáculos que desafiam Roma e chocam a elite.",
    "video_url": "http://cinetop.co.mz:8330/film/SpartacusHouseofAshurEpisode3.mp4",
    "duration": "55m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6347",
    "title": "Spartacus: House of Ashur - Episódio 4 - Episode 4",
    "image": "",
    "description": "E se Ashur tivesse sobrevivido e ganhado o ludus onde antes sangrou? Com Achillia, uma gladiadora, ele cria espetáculos que desafiam Roma e chocam a elite.",
    "video_url": "http://cinetop.co.mz:8330/film/SpartacusHouseofAshurEpisode4.mp4",
    "duration": "57m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5602",
    "title": "Fighter - Episódio 1 - Episode 1",
    "image": "",
    "description": "Um líder de esquadrão brilhante, mas imprudente, e sua equipe de pilotos de elite enfrentam perigos e demônios internos ao se unirem para uma missão mortal.",
    "video_url": "http://cinetop.co.mz:8330/film/Fighter2024Eps1.MP4",
    "duration": "86m",
    "release_year": "2024",
    "categories": "Séries, Novos Filmes, Dublagem, Acção",
    "cast": [
      "Hrithik Roshan",
      "Anil Kapoor",
      "Deepika Padukone"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5603",
    "title": "Fighter - Episódio 2 - Episode 2",
    "image": "",
    "description": "Um líder de esquadrão brilhante, mas imprudente, e sua equipe de pilotos de elite enfrentam perigos e demônios internos ao se unirem para uma missão mortal.",
    "video_url": "http://cinetop.co.mz:8330/film/Fighter2024Eps2.MP4",
    "duration": "78m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5925",
    "title": "Matéria Escura - Episódio 1 - Are You Happy in Your Life?",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode1AreYouHappyinYourLife.mp4",
    "duration": "46m",
    "release_year": "2024",
    "categories": "Séries, Dublagem, Ficção Científica",
    "cast": [
      "Joel Edgerton",
      "Jennifer Connelly",
      "Alice Braga"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5926",
    "title": "Matéria Escura - Episódio 2 - Trip of a Lifetime",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode2TripofaLifetime.mp4",
    "duration": "53m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5927",
    "title": "Matéria Escura - Episódio 3 - The Box",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode3TheBox.mp4",
    "duration": "49m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5928",
    "title": "Matéria Escura - Episódio 4 - The Corridor",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode4TheCorridor.mp4",
    "duration": "59m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5929",
    "title": "Matéria Escura - Episódio 5 - Worldless",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode5Worldless.mp4",
    "duration": "55m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5930",
    "title": "Matéria Escura - Episódio 6 - Superposition",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode6Superposition.mp4",
    "duration": "54m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5931",
    "title": "Matéria Escura - Episódio 7 - In the Fires of Dead Stars",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode7IntheFiresofDeadStars.mp4",
    "duration": "51m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5932",
    "title": "Matéria Escura - Episódio 8 - Jupiter",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode8Jupiter.mp4",
    "duration": "47m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5933",
    "title": "Matéria Escura - Episódio 9 - Entanglement",
    "image": "",
    "description": "Jason Dessen é sequestrado para uma versão alternativa de sua vida. Em busca de voltar para sua verdadeira família, ele embarca em uma jornada angustiante para salvá-los do inimigo mais terrível que se possa imaginar: ele mesmo.",
    "video_url": "http://cinetop.co.mz:8330/film/MateriaEscuraEpisode9Entanglement.mp4",
    "duration": "58m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6249",
    "title": "Contagem Regressiva - Episódio 1 - Teeth in the Bone",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode1TeethintheBone.mp4",
    "duration": "53m",
    "release_year": "2025",
    "categories": "Séries, Dublagem, Acção",
    "cast": [
      "Jensen Ackles",
      "Jessica Camacho",
      "Eric Dane"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6250",
    "title": "Contagem Regressiva - Episódio 2 - Dead Lots of Times",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode2DeadLotsofTimes.mp4",
    "duration": "50m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6251",
    "title": "Contagem Regressiva - Episódio 3 - Happy Birthday Final",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode3HappyBirthdayFinal.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6252",
    "title": "Contagem Regressiva - Episódio 4 - Bite 'Em Down",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode4BiteEmDown.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6253",
    "title": "Contagem Regressiva - Episódio 5 - Blurred Edges",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode5BlurredEdges.mp4",
    "duration": "53m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6254",
    "title": "Contagem Regressiva - Episódio 6 - A Needle or a Bullet",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode6ANeedleoraBullet.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6270",
    "title": "Contagem Regressiva - Episódio 7 - Nothing Else Helps",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode7NothingElseHelps.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6271",
    "title": "Contagem Regressiva - Episódio 8 - The Nail in the Chair",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode8TheNailintheChair.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6272",
    "title": "Contagem Regressiva - Episódio 9 - 10-33",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode91033.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6273",
    "title": "Contagem Regressiva - Episódio 10 - The Muzzle Pile",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode10TheMuzzlePile.mp4",
    "duration": "48m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6274",
    "title": "Contagem Regressiva - Episódio 11 - Run",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode11Run.mp4",
    "duration": "47m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6275",
    "title": "Contagem Regressiva - Episódio 12 - This Is His Signature",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode12ThisIsHisSignature.mp4",
    "duration": "46m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6276",
    "title": "Contagem Regressiva - Episódio 13 - Your People Are in Danger",
    "image": "",
    "description": "Quando um agente do Departamento de Segurança Nacional é morto à luz do dia, o detetive da Polícia de Los Angeles Mark Meachum é recrutado para uma força-tarefa com agentes disfarçados de todas as agências de segurança para investigar. Mas a caçada ao assassino revela uma trama mais sinistra do que todos poderiam imaginar, dando início a uma corrida contra o tempo para salvar uma cidade inteira.",
    "video_url": "http://cinetop.co.mz:8330/film/ContagemRegressivaEpisode13YourPeopleAreinDanger.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6234",
    "title": "Terra da Máfia - Episódio 1 - Stick or Twist",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode1StickorTwist.mp4",
    "duration": "60m",
    "release_year": "2025",
    "categories": "Séries, Novos Filmes, Dublagem, Acção",
    "cast": [
      "Tom Hardy",
      "Pierce Brosnan",
      "Paddy Considine"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6235",
    "title": "Terra da Máfia - Episódio 2 - Jigsaw Puzzle",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode2JigsawPuzzle.mp4",
    "duration": "52m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6236",
    "title": "Terra da Máfia - Episódio 3 - Plan B",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode3PlanB.mp4",
    "duration": "47m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6237",
    "title": "Terra da Máfia - Episódio 4 - Rat Trap",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode4RatTrap.mp4",
    "duration": "41m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6238",
    "title": "Terra da Máfia - Episódio 5 - Funeral for a Friend",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode5FuneralforaFriend.mp4",
    "duration": "41m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6239",
    "title": "Terra da Máfia - Episódio 6 - Antwerp Blues",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode6AntwerpBlues.mp4",
    "duration": "43m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6240",
    "title": "Terra da Máfia - Episódio 7 - The Crossroads",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode7TheCrossroads.mp4",
    "duration": "40m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6241",
    "title": "Terra da Máfia - Episódio 8 - Helter Skelter",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode8HelterSkelter.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6242",
    "title": "Terra da Máfia - Episódio 9 - Beggars Banquet",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode9BeggarsBanquet.mp4",
    "duration": "47m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6243",
    "title": "Terra da Máfia - Episódio 10 - The Beast in Me",
    "image": "",
    "description": "O poder está pronto para apreensões como os Harrigans e Stevensons, duas famílias de crimes de Londres, confronto em uma batalha de matar ou ser morto que ameaça derrubar impérios e arruinar vidas. Apanhado no fogo cruzado é Harry Da Souza, o \"fixer\" inteligente de rua tão perigoso como ele é bonito, que sabe muito bem onde as lealdades mentem quando as forças opostas colidem. Como o reino sobe contra o reino, as linhas serão atravessadas - e a única graça salvífica é uma garantia de aposta-sua-vida: a família acima de tudo.",
    "video_url": "http://cinetop.co.mz:8330/film/TerradaMafiaEpisode10TheBeastinMe.mp4",
    "duration": "55m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6148",
    "title": "Star Wars: Andor - Season 1 - Episódio 1 - Kassa",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode1Kassa.mp4",
    "duration": "39m",
    "release_year": "2025",
    "categories": "Séries, Dublagem, Ficção Científica",
    "cast": [
      "Diego Luna",
      "Stellan Skarsgård",
      "Kyle Soller"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6149",
    "title": "Star Wars: Andor - Season 1 - Episódio 2 - That Would Be Me",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode2ThatWouldBeMe.mp4",
    "duration": "35m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6150",
    "title": "Star Wars: Andor - Season 1 - Episódio 3 - Reckoning",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode3Reckoning.mp4",
    "duration": "40m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6151",
    "title": "Star Wars: Andor - Season 1 - Episódio 4 - Aldhani",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode4Aldhani.mp4",
    "duration": "46m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6152",
    "title": "Star Wars: Andor - Season 1 - Episódio 5 - The Axe Forgets",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode5TheAxeForgets.mp4",
    "duration": "43m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6153",
    "title": "Star Wars: Andor - Season 1 - Episódio 6 - The Eye",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode6TheEye.mp4",
    "duration": "50m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6154",
    "title": "Star Wars: Andor - Season 1 - Episódio 7 - Announcement",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode7Announcement.mp4",
    "duration": "50m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6155",
    "title": "Star Wars: Andor - Season 1 - Episódio 8 - Narkina 5",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode8Narkina5.mp4",
    "duration": "53m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6156",
    "title": "Star Wars: Andor - Season 1 - Episódio 9 - Nobody's Listening!",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode9NobodysListening.mp4",
    "duration": "46m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6157",
    "title": "Star Wars: Andor - Season 1 - Episódio 10 - One Way Out",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode10OneWayOut.mp4",
    "duration": "42m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6158",
    "title": "Star Wars: Andor - Season 1 - Episódio 11 - Daughter of Ferrix",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode11DaughterofFerrix.mp4",
    "duration": "42m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6159",
    "title": "Star Wars: Andor - Season 1 - Episódio 12 - Rix Road",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason1Episode12RixRoad.mp4",
    "duration": "54m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6160",
    "title": "Star Wars: Andor-Season 2 - Episódio 1 - One Year Later",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode1OneYearLater.mp4",
    "duration": "50m",
    "release_year": "2025",
    "categories": "Séries, Dublagem, Ficção Científica",
    "cast": [
      "Diego Luna",
      "Stellan Skarsgård",
      "Kyle Soller"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6161",
    "title": "Star Wars: Andor-Season 2 - Episódio 2 - Sagrona Teema",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode2SagronaTeema.mp4",
    "duration": "44m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6162",
    "title": "Star Wars: Andor-Season 2 - Episódio 3 - Harvest",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode3Harvest.mp4",
    "duration": "52m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6163",
    "title": "Star Wars: Andor-Season 2 - Episódio 4 - Ever Been to Ghorman?",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode4EverBeentoGhorman.mp4",
    "duration": "53m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6164",
    "title": "Star Wars: Andor-Season 2 - Episódio 5 - I Have Friends Everywhere",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode5IHaveFriendsEverywhere.mp4",
    "duration": "53m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6165",
    "title": "Star Wars: Andor-Season 2 - Episódio 6 - What a Festive Evening",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode6WhataFestiveEvening.mp4",
    "duration": "54m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6166",
    "title": "Star Wars: Andor-Season 2 - Episódio 7 - Messenger",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode7Messenger.mp4",
    "duration": "43m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6167",
    "title": "Star Wars: Andor-Season 2 - Episódio 8 - Who Are You?",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode8WhoAreYou.mp4",
    "duration": "46m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6168",
    "title": "Star Wars: Andor-Season 2 - Episódio 9 - Welcome to the Rebellion",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode9WelcometotheRebellion.mp4",
    "duration": "58m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6213",
    "title": "Star Wars: Andor-Season 2 - Episódio 10 - Make It Stop",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode10MakeItStop.mp4",
    "duration": "48m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6214",
    "title": "Star Wars: Andor-Season 2 - Episódio 11 - Who Else Knows?",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode11WhoElseKnows.mp4",
    "duration": "42m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6215",
    "title": "Star Wars: Andor-Season 2 - Episódio 12 - Jedha, Kyber, Erso",
    "image": "",
    "description": "Numa era repleta de perigos, enganos e intriga, Cassian Andor vai descobrir a diferença que pode fazer na luta contra o tirânico Império Galático. Embarca numa jornada destinada a torná-lo um herói da Rebelião.",
    "video_url": "http://cinetop.co.mz:8330/film/StarWarsAndorSeason2Episode12JedhaKyberErso.mp4",
    "duration": "45m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6080",
    "title": "BLUE LOCK - Episódio 1 - Dream",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode1Dream.mp4",
    "duration": "24m",
    "release_year": "2022",
    "categories": "Séries, Animação",
    "cast": [
      "Kazuki Ura",
      "Tasuku Kaito",
      "Yuki Ono"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6081",
    "title": "BLUE LOCK - Episódio 2 - Monster",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode2Monster.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6082",
    "title": "BLUE LOCK - Episódio 3 - Soccer's \"Zero\"",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode3SoccersZero.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6083",
    "title": "BLUE LOCK - Episódio 4 - Premonition and Intuition",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode4PremonitionandIntuition.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6084",
    "title": "BLUE LOCK - Episódio 5 - To Be Reborn",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode5ToBeReborn.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6085",
    "title": "BLUE LOCK - Episódio 6 - I'm Sorry",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode6ImSorry.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6086",
    "title": "BLUE LOCK - Episódio 7 - Rush",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode7Rush.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6087",
    "title": "BLUE LOCK - Episódio 8 - The Formula for Goals",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode8TheFormulaforGoals.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6088",
    "title": "BLUE LOCK - Episódio 9 - Awakening",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode9Awakening.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6089",
    "title": "BLUE LOCK - Episódio 10 - Just the Way It Is",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode10JusttheWayItIs.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6090",
    "title": "BLUE LOCK - Episódio 11 - The Final Piece",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode11TheFinalPiece.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6091",
    "title": "BLUE LOCK - Episódio 12 - The Second Selection",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode12TheSecondSelection.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6092",
    "title": "BLUE LOCK - Episódio 13 - TOP3",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode13TOP3.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6093",
    "title": "BLUE LOCK - Episódio 14 - The Geniuses and the Average Joes",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode14TheGeniusesandtheAverageJoes.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6094",
    "title": "BLUE LOCK - Episódio 15 - Devour",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode15DevourReupload.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6095",
    "title": "BLUE LOCK - Episódio 16 - Tri-Fusion",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode16TriFusionReupload.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6096",
    "title": "BLUE LOCK - Episódio 17 - Donkey",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode17Donkey.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6097",
    "title": "BLUE LOCK - Episódio 18 - The Stage for the Lead",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode18TheStagefortheLead.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6098",
    "title": "BLUE LOCK - Episódio 19 - Dancing Boy",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode19DancingBoy.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6099",
    "title": "BLUE LOCK - Episódio 20 - Super Link-Up Play",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode20SuperLinkUpPlay.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6100",
    "title": "BLUE LOCK - Episódio 21 - I'm Not There",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode21ImNotThere.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6101",
    "title": "BLUE LOCK - Episódio 22 - Voice",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode22Voice.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6102",
    "title": "BLUE LOCK - Episódio 23 - Luck",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode23Luck.mp4",
    "duration": "24m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6103",
    "title": "BLUE LOCK - Episódio 24 - The Time Has Come",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode24TheTimeHasCome.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6104",
    "title": "BLUE LOCK - Episódio 25 - Tryouts",
    "image": "",
    "description": "Após sofrer um vexame na Copa do Mundo de 2018, a seleção japonesa sofre para se recompor. Falta ao time um artilheiro, uma estrela capaz de guiá-los à vitória. Com o intuito de criar um atacante com fome de bola e sede de vitória, capaz de virar jogos tidos como impossíveis, a Confederação Japonesa de Futebol reune 300 dos melhores jogadores de base do país em um só lugar. Centenas de jovens vão se enfrentar numa batalha de músculos e de egos para provar que são os melhores.",
    "video_url": "http://cinetop.co.mz:8330/film/BLUELOCKEpisode25Tryouts.mp4",
    "duration": "25m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5855",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 1 - Elven Kings Under the Sky",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode1ElvenKingsUndertheSky.mp4",
    "duration": "76m",
    "release_year": "2024",
    "categories": "Séries, Filmes Populares, Novos Filmes, Dublagem, Aventura",
    "cast": [
      "Charlie Vickers",
      "Morfydd Clark",
      "Robert Aramayo"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5856",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 2 - Where the Stars Are Strange",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode2WheretheStarsAreStrange.mp4",
    "duration": "62m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5857",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 3 - The Eagle and the Sceptre",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode3TheEagleandtheSceptre.mp4",
    "duration": "66m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5858",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 4 - Eldest",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode4Eldest.mp4",
    "duration": "65m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5859",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 5 - Halls of Stone",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode5HallsofStone.mp4",
    "duration": "61m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5860",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 6 - Where Is He?",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode6WhereIsHe.mp4",
    "duration": "63m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5861",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 7 - Doomed to Die",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode7DoomedtoDie.mp4",
    "duration": "72m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "5889",
    "title": "O Senhor dos Anéis: Os Anéis de Poder- Season 2 - Episódio 8 - Episode 8",
    "image": "",
    "description": "Tendo início em uma época de relativa paz, a série acompanha um grupo de personagens que enfrenta o ressurgimento do mal na Terra-média. Das profundezas escuras das Montanhas de Névoa, das majestosas florestas de Lindon, do belíssimo reino da ilha de Númenor, até os confins do mapa, esses reinos e personagens criarão legados que permanecerão vivos muito além de suas partidas.",
    "video_url": "http://cinetop.co.mz:8330/film/OSenhordosAneisOsAneisdePoderSeason2Episode8.mp4",
    "duration": "73m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6118",
    "title": "Solo Leveling - Episódio 1 - I'm Used to It",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode1ImUsedtoIt.mp4",
    "duration": "23m",
    "release_year": "2024",
    "categories": "Séries, Animação",
    "cast": [
      "Taito Ban",
      "Genta Nakamura",
      "Haruna Mikawa"
    ],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6119",
    "title": "Solo Leveling - Episódio 2 - If I Had One More Chance",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode2IfIHadOneMoreChance.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6120",
    "title": "Solo Leveling - Episódio 3 - It's Like a Game",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode3ItsLikeaGame.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6121",
    "title": "Solo Leveling - Episódio 4 - I've Gotta Get Stronger",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode4IveGottaGetStronger.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6122",
    "title": "Solo Leveling - Episódio 5 - A Pretty Good Deal",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode5APrettyGoodDeal.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6123",
    "title": "Solo Leveling - Episódio 6 - The Real Hunt Begins",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode6TheRealHuntBegins.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6124",
    "title": "Solo Leveling - Episódio 7 - Let's See How Far I Can Go",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode7LetsSeeHowFarICanGo.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6125",
    "title": "Solo Leveling - Episódio 8 - This Is Frustrating",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode8ThisIsFrustrating.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  },
  {
    "tipo": "serie",
    "id": "6126",
    "title": "Solo Leveling - Episódio 9 - You've Been Hiding Your Skills",
    "image": "",
    "description": "Há mais de uma década, surgiu uma misteriosa passagem chamada \"portal\", que conecta este mundo a uma dimensão diferente, o que fez com que pessoas despertassem poderes únicos… e essas pessoas são chamadas de \"caçadores\". Os caçadores usam seus poderes sobre-humanos para conquistar masmorras dentro dos portais e assim ganhar a vida. Sung Jinwoo, um caçador de nível baixo, é considerado o caçador mais fraco de toda a humanidade. Certo dia, ele se depara com uma \"masmorra dupla\", que tem uma masmorra de nível alto escondida dentro de uma masmorra de nível baixo. Diante de um Jinwoo gravemente ferido, surge uma misteriosa missão! À beira da morte, Jinwoo decide aceitar essa missão, tornando-se assim a única pessoa capaz de subir de nível!",
    "video_url": "http://cinetop.co.mz:8330/film/SoloLevelingEpisode9YouveBeenHidingYourSkills.mp4",
    "duration": "23m",
    "release_year": "",
    "categories": "",
    "cast": [],
    "lang": "Português"
  }
];